#!/usr/bin/ash


# # # # # # # USER SETTINGS

# These should be a number from 0 to 15

BACKGROUND=0
WELCOME=5
INPUTBOX=4

# # # # # # # # # # # # # #


run_hook() {
    bk="\x1b[48;5;${BACKGROUND}m"
    we="\x1b[48;5;${WELCOME}m"
    in="\x1b[48;5;${INPUTBOX}m"

    p="$we  $bk"  		# single pixel
    s="$we  "	    		# start pixel row
    e="  $bk"	    		# end pixel row
    non="\x1b[0m"		# reset all settings
    fill="\033[K"   		# fill to end of line

    echo -e "$b14\n$fill\n$fill\n$fill\n$fill\n$fill\n$fill\n$fill\n$fill\n$fill\n$fill\n$fill\n$fill\n$fill\n$fill\n$fill\n$fill"
    echo -e "                                                                                                  $s$e$fill"
    echo -e "                                                                   $p          $p                   $p$fill"
    echo -e "                                                                   $p          $p                   $p$fill"
    echo -e "                                                                   $p          $p    $s    $e       $p            $s    $e        $s    $e      $s  $e  $s$e      $s    $e$fill"
    echo -e "                                                                   $p    $p    $p  $p        $p     $p          $p        $p    $p        $p    $p    $p    $p  $p        $p$fill"
    echo -e "                                                                   $p    $p    $p  $s        $e     $p          $p              $p        $p    $p    $p    $p  $s        $e$fill"
    echo -e "                                                                   $p    $p    $p  $p               $p          $p              $p        $p    $p    $p    $p  $p$fill"
    echo -e "                                                                   $p  $p  $p  $p  $p               $p          $p        $p    $p        $p    $p    $p    $p  $p$fill"
    echo -e "                                                                   $s$e      $s$e    $s      $e       $s  $e      $s    $e        $s    $e      $p    $p    $p    $s      $e$fill"
    echo -e "$fill\n$fill\n$fill\n$fill"
    echo -e "                                                                                             $in                                                      $bk$fill"
    echo -e "                                                                                             $in  $bk                                                  $in  $bk$fill"
    echo -e "                                                                                             $in                                                      $bk$fill"
    echo -e "$fill\n$fill\n$fill\n$fill\n$fill\n$fill\n$fill\n$fill\n$fill\n$fill\n$fill\n$fill\n$fill\n$fill\n$fill\n$fill\n$fill\n$fill\n$fill\n$fill\n$fill\n$fill\n$fill\n$fill\n$fill\n$fill\n$fill\n$fill\n$fill\n$fill\n$fill\n$fill\n$fill"

    # move cursor to input box
    echo -ne "\x1b[32;96H"
}
