#!/bin/bash

build() {
    (
	WELCOME_FG=5
	WELCOME_BG=0
	WELCOME_IN=4

        [[ -s /etc/vconsole.conf ]] && . /etc/vconsole.conf

	is_int() { test "$1" -ge 0 -a "$1" -le 15; }
	is_int $WELCOME_FG || exit 1
	is_int $WELCOME_BG || exit 1
	is_int $WELCOME_IN || exit 1

	echo "WELCOME_FG=$WELCOME_FG" >> "$BUILDROOT/welcome"
	echo "WELCOME_BG=$WELCOME_BG" >> "$BUILDROOT/welcome"
	echo "WELCOME_IN=$WELCOME_IN" >> "$BUILDROOT/welcome"

    ) || {
	echo "welcome: /etc/vconsole.conf configuration error"
	exit 1
    }

    add_runscript
}

help() {
    cat <<HELPEOF
Prints the word "Welcome" in large letters and draws a box around the input for
the encrypt hook and output of the fsck hook.
HELPEOF
}
